import React from "react";
import { Metadata } from "next";
import { Footer, SubFooter } from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Digital Marketing",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
      <Footer />
      <SubFooter />
    </>
  );
}
