import React from "react";
import { Metadata } from "next";
import { AddClientPanel } from "@/context/business-credit/panel/add.client.panel";
import { AccountBanner } from "@/components/business-account-elements/account.banner";
export const metadata: Metadata = {
  title: "Fundability Foundation",
  description: "Generated by create next app",
};

let activeState = "improve";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
        <div className="flex flex-col justify-center w-[50%]">
          {children}
        </div>

    </>

  );
}
