import React from "react";
import { Metadata } from "next";
import Sider from "../../../components/admin/Sider";

export const metadata: Metadata = {
  title: "Choose From Below Options",
  description: "Generated by create next app",
};

let activeState = "dashboard";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>


      <div className="w-full h-full flex ">
        <Sider />

        <div className="w-full h-full">{children}</div>
      </div>

      <p className="flex w-full justify-center content-center items-center text-red-400 py-4 bg-white">
        @2024. Official Website
      </p>
    </>
  );
}
