import React from "react";
import { Metadata } from "next";
import { Footer, SubFooter } from "@/components/footer/footer";
import { BusinessFundingScreen } from "@/screen/leads/business-funding/business.funding.screen";

export const metadata: Metadata = {
  title: "Business Funding",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <BusinessFundingScreen>{children}</BusinessFundingScreen>
      <Footer />
      <SubFooter />
    </>
  );
}
