import React from "react";
import { Metadata } from "next";
import { AddClientPanel } from "@/context/business-credit/panel/add.client.panel";
import { AccountBanner } from "@/components/business-account-elements/account.banner";
export const metadata: Metadata = {
  title: "Fundability Foundation",
  description: "Generated by create next app",
};

let activeState = "";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="flex w-full justify-between">
        {children}
      </div>
      <p className="flex w-full justify-center content-center items-center text-red-400 py-4">@2024. Official TGIscalme.com Website</p>

    </>

  );
}
