import React from "react";
import { Metadata } from "next";
import { AdminPanel } from "@/context/business-credit/panel/admin.panel";
export const metadata: Metadata = {
  title: "Current User",
  description: "Generated by create next app",
};

let activeState = "team";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="grid grid-cols-7 justify-between">
        <div className="flex col-start-1 col-span-1 w-full justify-start content-start bg-white">
          <AdminPanel activeState={activeState} />
        </div>
        <div className="flex col-start-2 col-span-7 justify-start pl-6">
          {children}
        </div>
      </div>
      <p className="flex w-full justify-center content-center items-center text-red-400 py-4 bg-white">@2024. Official TGIscalme.com Website</p>

    </>

  );
}
