import React from "react";
import { Metadata } from "next";
import { APContextProvider } from "@/context/business-credit/account-package/personal.account.pacakge.context";
export const metadata: Metadata = {
  title: "EMBARK ON YOUR 'BUSINESS CREDIT' SCALING JOURNEY",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <APContextProvider>
      <div className={"pb-0"}> {children}</div>
    </APContextProvider>
  );
}
